config/routes.rb
Sideheroes::Application.routes.draw do
  resources :line_items

  resources :watchlists

  get "store/index"
  `get "store/index"`
  resources :projects

  root 'store#index', as: 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :project
  belongs_to :watchlist
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, :description, :headline, :project_type, presence: true
  validates :title, uniqueness: true
  
  def self.latest
    Project.order(:updated_at).last
  end
  
  

end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/concerns/current_watchlist.rb
module CurrentWatchlist
  extend ActiveSupport::Concern
  
  private
  
  def set_watchlist
    @watchlist = Watchlist.find(session[:watchlist_id])
  rescue ActiveRecord::RecordNotFound
    @watchlist = Watchlist.create # If no watchlist can be found create a new one
    session[:watchlist_id] = @watchlist.id  
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentWatchlist # include this module in order to provide access to its methods
  before_action :set_watchlist, only: [:create] # call the set_cart method before allowing the create method to be called
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  
  # Below we are changing the create method to create 
  def create
    project = Project.find(params[:project_id]) #project_id passed with the post command and collected in the params object
    # @line_item = LineItem.new(line_item_params)
    @line_item = @watchlist.line_items.build(project: project)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.watchlist, notice: 'Line item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:project_id, :watchlist_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end





  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :current_team_size, :desired_team_size, :headline, :project_type, :project_length, :primary_technology, :secondary_technology, :tertiary_technology)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  
  def index
    @projects = Project.order(:title)
  end
 
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :set_watchlist, only: [:show, :edit, :update, :destroy]

  # GET /watchlists
  # GET /watchlists.json
  def index
    @watchlists = Watchlist.all
  end

  # GET /watchlists/1
  # GET /watchlists/1.json
  def show
  end

  # GET /watchlists/new
  def new
    @watchlist = Watchlist.new
  end

  # GET /watchlists/1/edit
  def edit
  end

  # POST /watchlists
  # POST /watchlists.json
  def create
    @watchlist = Watchlist.new(watchlist_params)

    respond_to do |format|
      if @watchlist.save
        format.html { redirect_to @watchlist, notice: 'Watchlist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @watchlist }
      else
        format.html { render action: 'new' }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watchlists/1
  # PATCH/PUT /watchlists/1.json
  def update
    respond_to do |format|
      if @watchlist.update(watchlist_params)
        format.html { redirect_to @watchlist, notice: 'Watchlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watchlists/1
  # DELETE /watchlists/1.json
  def destroy
    @watchlist.destroy
    respond_to do |format|
      format.html { redirect_to watchlists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watchlist
      @watchlist = Watchlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watchlist_params
      params[:watchlist]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sideheroes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
</head>
<body class='<%= controller.controller_name%>'>
	<div id="banner">
		<a href="/"><%= image_tag("logo.png")%></a> <!-- link to the root of the site -->
  </div>

	<div id="columns">
	  <div id="side">
	  	<ul>
	  		<li><a href="/">Home</a></li>
	  		<li><a href="watchlists">Watchlists</a></li>
	  		<li><a href="projects">Projects (Old)</a></li>
	  		<li><a href="store">Projects</a></li>
		
	  		<li>You were last here today, at <%= Time.now %></li>
	  	</ul>
	  </div>	
		
	</div>
	<div id="main">
	  <%= yield %>
	</div>
	<footer>
		<p>&copy; 2014</p>
	</footer>

</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :watchlist_id %><br>
    <%= f.text_field :watchlist_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Watchlist</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.project %></td>
        <td><%= line_item.watchlist %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @line_item.project %>
</p>

<p>
  <strong>Watchlist:</strong>
  <%= @line_item.watchlist %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :current_team_size %><br>
    <%= f.number_field :current_team_size %>
  </div>
  <div class="field">
    <%= f.label :desired_team_size %><br>
    <%= f.number_field :desired_team_size %>
  </div>
  <div class="field">
    <%= f.label :headline %><br>
    <%= f.text_area :headline %>
  </div>
  <div class="field">
  	<%= f.label :project_type %>
  	<%= f.text_area :project_type %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
	<% @projects.each do |project| %>
		<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
			<td class="list_description">
				<dl>
					<dt> <%= project.title %></dt>
					<dd> <%= truncate (strip_tags project.description), length: 50 %></dd>
				</dl>
			</td>
			<td> <%= project.headline %></td> <!-- headline -->
			<td> <%= project.current_team_size%> </td> <!-- current team size -->
			<td> <%= project.desired_team_size%> </td> <!-- desired team size -->
			<td class="list_actions">
				<%= link_to 'Show', project %><br/>
				<%= link_to 'Edit', edit_project_path(project) %><br/>
				<%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?'}%>
			</td>
				
		</tr>
	<% end %>
</table>>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to our project</h1>
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Current team size:</strong>
  <%= @project.current_team_size %>
</p>

<p>
  <strong>Desired team size:</strong>
  <%= @project.desired_team_size %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/store/index.html.erb
<% # notice = "A piece of string" %>
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Projects Offered</h1>

<% cache ['store', Project.latest] do %>
	<% @projects.each do |project| %>
	  <% cache ['entry', project] do %>
		  <div class="entry">
		    <h3><%= project.title %></h3>
		    <h3><%= link_to project.title, @project %></h3>
		    <%= sanitize(project.description) %>
		    
		    <!-- routes matches a post request to a controller to that controller's create method-->
		    <%= button_to 'Add to Watchlist', line_items_path(project_id: project) %> 
		  </div>  
	    
	    
		<% end %>
	<% end %>
<% end %>

	

app/views/watchlists/_form.html.erb
<%= form_for(@watchlist) do |f| %>
  <% if @watchlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@watchlist.errors.count, "error") %> prohibited this watchlist from being saved:</h2>

      <ul>
      <% @watchlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/watchlists/edit.html.erb
<h1>Editing watchlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @watchlist %> |
<%= link_to 'Back', watchlists_path %>

app/views/watchlists/index.html.erb
<h1>Listing watchlists</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @watchlists.each do |watchlist| %>
      <tr>
        <td><%= link_to 'Show', watchlist %></td>
        <td><%= link_to 'Edit', edit_watchlist_path(watchlist) %></td>
        <td><%= link_to 'Destroy', watchlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watchlist', new_watchlist_path %>

app/views/watchlists/new.html.erb
<h1>New watchlist</h1>

<%= render 'form' %>

<%= link_to 'Back', watchlists_path %>

app/views/watchlists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_watchlist_path(@watchlist) %> |
<%= link_to 'Back', watchlists_path %>